### PR TITLE
Backend/api fix

### PR DESCRIPTION
**Pull request by rolandbogdan**
Can we just skip the repo layer pls?

### CODE REVIEW

**Review by IIB3nceII — APPROVED** [review]

**Review by devv77 — COMMENTED** [review]
Can be the cause of something that its not the same expected output.  But only it seems that. @IIB3nceII could you check this please? If we have a method to do the samething as the linq, i think we should prioritize to use the method. So we need to have the same output. It can causeother problems later. Thanks

**Review by belhart — APPROVED** [review]

**Comment by IIB3nceII** [comment]
I am okay with that @rolandbogdan @devv77

**Comment by devv77** [comment]
Then it gets my approval too. Thanks guys

**Review by devv77 — APPROVED** [review]
Seems fine then. Thanks for the answers

**Review by IIB3nceII — APPROVED** [review]

**Comment by IIB3nceII** [comment]
Please pull the develop branch first, resolve the conflicts and then reopen the pr.

**Pull request merged**
